### ISSUE TITLE
Add Terraform resources for Entities in Backstage

### ISSUE THREAD

**Issue by phclark** [tdabasinskas/terraform-provider-backstage#137]
Is it possible to create Entities directly through the `/api/catalog/entities` API, as opposed to indirectly via Location?

For example, I'd like to be able to use your Terraform Provider to create Component Entities for Terraform Cloud Workspaces (which we provision using modules), then take advantage of this Backstage Plugin, https://backstage.spotify.com/marketplace/globallogic/plugin/terraform, to view and inspect TFC runs from Backstage. I'd love to be able to automate away the process of creating catalog-info.yaml files for each workspace :)

**Comment by tdabasinskas** [comment]
Hi @phclark,

[Backstage API](https://backstage.io/docs/features/software-catalog/software-catalog-api/#post-refresh) does not support directly creating entities.

Maybe you could use [`github_repository_file` resource from GitHub provider](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_file) - create `catalog-info.yaml` file defining the component in a GitHub repository and register it via [`backstage_location` resource](https://registry.terraform.io/providers/tdabasinskas/backstage/latest/docs/resources/location).
