### ISSUE TITLE
Add resource Components

### ISSUE THREAD

**Issue by clementblaise** [tdabasinskas/terraform-provider-backstage#38]
Hello @tdabasinskas awesome that you started this! Right now it seems like there is only support for the Location resources, are you planning on expanding the coverage? I was interested in managing Components

**Comment by tdabasinskas** [comment]
Hi @clementblaise,

Components can be discovered from `catalog-info` files, so, as long as you have auto-discovey (e.g., in GitHub) configured on your Backstage instance, you can use some other Terraform module to push `catalog-info` files. You can also use `Location` resource to register location to the Component defined in specific `catalog-info` file.

The [official Backstage REST API documentation](https://backstage.io/docs/features/software-catalog/software-catalog-api/) provides no information on managing catalog resources.

**Comment by clementblaise** [comment]
Thanks for your response @tdabasinskas and sorry for the misunderstanding. Indeed Backstage use a pull model to manage Entities, the preferred way is either use [custom entity provider](https://backstage.io/docs/features/software-catalog/external-integrations#custom-entity-providers) or a [custom processor](https://backstage.io/docs/features/software-catalog/external-integrations#custom-processors)
