### ISSUE TITLE
base_url validation doesn't allow valid TLDs

### ISSUE THREAD

**Issue by simontabor** [tdabasinskas/terraform-provider-backstage#72]
https://github.com/tdabasinskas/terraform-provider-backstage/blob/main/backstage/provider.go#L61

`.engineer` is a valid TLD and the regex fails, preventing use of the plugin.

I don't think validating URLs is terribly useful for this provider, especially not using regex - an invalid URL can simply be allowed to result in errors further down the line (connection failure)

## Reproduce

```hcl
provider "backstage" {
  base_url = "https://my-backstage-instance.engineer"
}
```

```
│ Error: Invalid Attribute Value Match
│
│   with provider["registry.terraform.io/tdabasinskas/backstage"],
│   on main.tf line 51, in provider "backstage":
│   51:   base_url = "https://my-backstage-instance.engineer"
│
│ Attribute base_url must be a valid URL, got: https://my-backstage-instance.engineer
```

**Comment by simontabor** [comment]
Using `BACKSTAGE_BASE_URL` bypasses the validation and allows it to proceed, which is a separate issue (it should be validated in the same way), but this allows me to proceed for now.

**Comment by tdabasinskas** [comment]
Sounds legit. Thanks for reporting these - will try to address then.
