### ISSUE TITLE
Allow setting custom headers on requests

### ISSUE THREAD

**Issue by simontabor** [tdabasinskas/terraform-provider-backstage#73]
We have a Backstage instance that's protected by CloudFlare, providing us an extra layer of protection.

To authenticate with the provider, we'd need to set headers for CloudFlare Service Auth on every request. I can see this being a common pattern across any authentication method - most of the time the Backstage API won't be public.

Proposal would be as follows:

```hcl
provider "backstage" {
  // ...
  header {
    name = "Authorization"
    value = "XXX"
  }
  header {
    // ...
  }
}
```

If there are any alternatives I'd be open to them. Generally I think this should be common enough to warrant supporting it in the provider, as the alternative is to run a proxy to add the relevant headers, but that adds a fair bit of complexity.

P.S. thank you for building this provider - 🤞 it's going to come in very handy for us!

**Comment by tdabasinskas** [comment]
Hey,

Could you try the newly released [v2.2.0](https://github.com/tdabasinskas/terraform-provider-backstage/releases/tag/v2.2.0) to see if it works as expected? It includes both `headers` functionality, and improvements for handling the base URL, you requested under #72 .

**Comment by simontabor** [comment]
Amazing, thank you so much for the speedy fixes + implementation.

I've just tested it out and no luck unfortunately. It seems like the headers are being added with additional quotes, causing authentication failures.

```hcl
provider "backstage" {
  base_url = "http://localhost:5050"
  headers = {
    testing = "value"
  }
}
```

Results in requests being made with a the header `testing="value"`, which is a literal value, it should be `testing=value`

**Comment by simontabor** [comment]
Works correctly when using env vars
`BACKSTAGE_HEADERS=testing=value terraform plan` - results in correct `testing=value` header being used

**Comment by tdabasinskas** [comment]
Thanks for testing this out. Confirm it's indeed a bug. Tested and #79 should fix it. 

Can you give it one more try with [v2.2.1](https://github.com/tdabasinskas/terraform-provider-backstage/releases/tag/v2.2.1)?
